### ISSUE TITLE
Creo que hay un Error en new-moodle.sh

### ISSUE THREAD

**Issue by sidlors** [bitumin/docker-moodle#1]
sh new-moodle.sh --version=32 --prefix=mdl32_
**new-moodle.sh: 19: new-moodle.sh: Syntax error: "(" unexpected**

**Comment by bitumin** [comment]
Creo que debería funcionar con bash en cualquier SO, si estás en linux prueba:
./new-moodle.sh --version=32 --prefix=mdl32_
Si estás en un OSX, quizá funcione con:
bash new-moodle.sh --version=32 --prefix=mdl32_

**Comment by sidlors** [comment]
el tema es el script mismo no si ejecuta o no;

Tenemos en la linea 19

# Dependencies validation
DEPENDENCIES=(
    mkdir
    dirname
    git
    docker
    docker-compose
    node
    npm
    php
    composer
    sed
)
 y al ejecutar, La Salida es;

> new-moodle.sh: line 19: syntax error: unexpected "("

**Comment by bitumin** [comment]
Si usas el intérprete bash no te dará ese error. A mí ese error me aparece cuando ejecuto el script con un intérprete dash (que no admite arrays).
En OSX, a mí me funciona usando:
`sh script.sh`
En Ubuntu, en cambio, tengo que usar:
`/bin/bash script.sh` o `./script.sh`, porque `/bin/sh` está asociado al intérprete dash.

**Comment by bitumin** [comment]
Asumo que se trataba de aquello que he comentado. Cierro el issue.
